version: "3"
services:
  sftp:
    image: atmoz/sftp:alpine
    container_name: sftp
    volumes:
        - "./data:/home/upload/:z"
        - "./config/id_rsa.pub:/home/upload/.ssh/keys/id_rsa.pub:ro"
        - "/etc/localtime:/etc/localtime:ro"
    ports:
        - "20222:22"
    command: upload:XXX:1001
